common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock
  username: <%= Settings.database.username %>
  password: <%= Settings.database.password %>
   
development:
  <<: *common
  database: blueprint_development

test:
  <<: *common
  database: blueprint_test

production:
  <<: *common
  database: blueprint_production
  host: 127.0.0.1
